/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import static com.Functionalities.DRIVER;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import java.awt.Toolkit;
/**
 *
 * @author Kibathi's
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    static Connection connection;
   
    public Admin() {
        initComponents();
        selectionShow(menu, expenses, sales, msales);
        DateFormat dateFomart = new SimpleDateFormat("yyyy-MM-dd");
        datePickerExpensesEntry.setFormats(dateFomart);
        datePickerExpensesSearch.setFormats(dateFomart);
        datePickerShowSales.setFormats(dateFomart);
        
//      -------------------Populating the table on display -----------------------------

       Functionalities.fetch(this, Functionalities.query_menu, menu_table);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base_pnl = new javax.swing.JPanel();
        nav_pnl = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        expenses = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        msales = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        switch_pnl = new javax.swing.JPanel();
        menu_pnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu_table = new javax.swing.JTable();
        additem_pnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        itemcode_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        price_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        type_combo = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        price_txt1 = new javax.swing.JTextField();
        btn_alterprice = new javax.swing.JButton();
        itemcode_txt1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        itemcode_txt2 = new javax.swing.JTextField();
        btn_removeitem = new javax.swing.JButton();
        expenses_pnl = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        expenses_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addexpense_pnl = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        description_txtfield = new javax.swing.JTextField();
        amount_txtfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        search_pnl = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        entryNo_txtfield = new javax.swing.JTextField();
        btn_removeExpense = new javax.swing.JButton();
        datePickerExpensesEntry = new org.jdesktop.swingx.JXDatePicker();
        datePickerExpensesSearch = new org.jdesktop.swingx.JXDatePicker();
        dsales_pnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sales_table = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        btn_searchDsales = new javax.swing.JButton();
        datePickerShowSales = new org.jdesktop.swingx.JXDatePicker();
        msales_pnl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        msalesTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        btnMsalesYearDisplay = new javax.swing.JButton();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        back_pnl = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator");
        setIconImage(Toolkit.getDefaultToolkit().getImage(Admin.class.getResource("/images/logo.png")));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expensesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expensesBtnMouseExited(evt);
            }
        });

        base_pnl.setBackground(new java.awt.Color(244, 176, 66));
        base_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav_pnl.setBackground(new java.awt.Color(244, 176, 66));
        nav_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(185, 244, 66));
        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jLabel1.setText("Menu");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        nav_pnl.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        expenses.setBackground(new java.awt.Color(185, 244, 66));
        expenses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        expenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expensesMouseClicked(evt);
            }
        });

        jLabel2.setText("Expenses");

        javax.swing.GroupLayout expensesLayout = new javax.swing.GroupLayout(expenses);
        expenses.setLayout(expensesLayout);
        expensesLayout.setHorizontalGroup(
            expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        expensesLayout.setVerticalGroup(
            expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        nav_pnl.add(expenses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, 110));

        sales.setBackground(new java.awt.Color(185, 244, 66));
        sales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
        });

        jLabel3.setText("Daily Sales");

        javax.swing.GroupLayout salesLayout = new javax.swing.GroupLayout(sales);
        sales.setLayout(salesLayout);
        salesLayout.setHorizontalGroup(
            salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        salesLayout.setVerticalGroup(
            salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        nav_pnl.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 110, 100));

        msales.setBackground(new java.awt.Color(185, 244, 66));
        msales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        msales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msalesMouseClicked(evt);
            }
        });

        jLabel17.setText("Monthly ");

        jLabel21.setText("Report");

        javax.swing.GroupLayout msalesLayout = new javax.swing.GroupLayout(msales);
        msales.setLayout(msalesLayout);
        msalesLayout.setHorizontalGroup(
            msalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msalesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(msalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        msalesLayout.setVerticalGroup(
            msalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msalesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        nav_pnl.add(msales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 110, 110));

        base_pnl.add(nav_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, -1));

        switch_pnl.setLayout(new java.awt.CardLayout());

        menu_pnl.setBackground(new java.awt.Color(244, 176, 66));

        menu_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "Name", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menu_table.setSelectionBackground(new java.awt.Color(255, 204, 102));
        jScrollPane1.setViewportView(menu_table);

        additem_pnl.setBackground(new java.awt.Color(244, 176, 66));
        additem_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                additem_pnlMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout additem_pnlLayout = new javax.swing.GroupLayout(additem_pnl);
        additem_pnl.setLayout(additem_pnlLayout);
        additem_pnlLayout.setHorizontalGroup(
            additem_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, additem_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        additem_pnlLayout.setVerticalGroup(
            additem_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additem_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("ItemCode");

        jLabel6.setText("Name");

        jLabel7.setText("Type");

        jLabel8.setText("Price");

        jLabel9.setText("Add Item");

        type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "breakfast", "snacks", "meals", "drinks" }));
        type_combo.setSelectedIndex(-1);

        jLabel22.setText("Alter Price");

        jLabel23.setText("ItemCode");

        jLabel24.setText("New Price");

        btn_alterprice.setText("OK");
        btn_alterprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterpriceActionPerformed(evt);
            }
        });

        jLabel25.setText("Remove Item");

        jLabel26.setText("ItemCode");

        btn_removeitem.setText("Remove");
        btn_removeitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeitemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_pnlLayout = new javax.swing.GroupLayout(menu_pnl);
        menu_pnl.setLayout(menu_pnlLayout);
        menu_pnlLayout.setHorizontalGroup(
            menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_pnlLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_pnlLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9))
                    .addGroup(menu_pnlLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel22))
                    .addGroup(menu_pnlLayout.createSequentialGroup()
                        .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menu_pnlLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(menu_pnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26))))
                        .addGap(26, 26, 26)
                        .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(additem_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type_combo, 0, 121, Short.MAX_VALUE)
                                .addComponent(name_txt)
                                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_alterprice)
                                    .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(price_txt1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(itemcode_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(price_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(itemcode_txt1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(itemcode_txt2, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(btn_removeitem)))
                    .addGroup(menu_pnlLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel25)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        menu_pnlLayout.setVerticalGroup(
            menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_pnlLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(additem_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(21, 21, 21)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(itemcode_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(price_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_alterprice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(9, 9, 9)
                .addGroup(menu_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(itemcode_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_removeitem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        switch_pnl.add(menu_pnl, "card4");

        expenses_pnl.setBackground(new java.awt.Color(244, 176, 66));

        expenses_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Entryno", "Date", "Description", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(expenses_table);
        if (expenses_table.getColumnModel().getColumnCount() > 0) {
            expenses_table.getColumnModel().getColumn(0).setPreferredWidth(0);
            expenses_table.getColumnModel().getColumn(1).setPreferredWidth(1);
            expenses_table.getColumnModel().getColumn(3).setPreferredWidth(1);
        }

        jLabel10.setText("Date");

        jLabel11.setText("Description");

        jLabel12.setText("Amount");

        addexpense_pnl.setBackground(new java.awt.Color(244, 176, 66));
        addexpense_pnl.setPreferredSize(new java.awt.Dimension(40, 40));
        addexpense_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addexpense_pnlMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add.png"))); // NOI18N

        javax.swing.GroupLayout addexpense_pnlLayout = new javax.swing.GroupLayout(addexpense_pnl);
        addexpense_pnl.setLayout(addexpense_pnlLayout);
        addexpense_pnlLayout.setHorizontalGroup(
            addexpense_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addexpense_pnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );
        addexpense_pnlLayout.setVerticalGroup(
            addexpense_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addexpense_pnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jLabel14.setText("Add Expense");

        jLabel15.setText("Search for date:");

        search_pnl.setBackground(new java.awt.Color(244, 176, 66));
        search_pnl.setPreferredSize(new java.awt.Dimension(40, 40));
        search_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_pnlMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-filled-40.png"))); // NOI18N

        javax.swing.GroupLayout search_pnlLayout = new javax.swing.GroupLayout(search_pnl);
        search_pnl.setLayout(search_pnlLayout);
        search_pnlLayout.setHorizontalGroup(
            search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        search_pnlLayout.setVerticalGroup(
            search_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel27.setText("Delete entry");

        jLabel28.setText("Entryno");

        btn_removeExpense.setText("Remove");
        btn_removeExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout expenses_pnlLayout = new javax.swing.GroupLayout(expenses_pnl);
        expenses_pnl.setLayout(expenses_pnlLayout);
        expenses_pnlLayout.setHorizontalGroup(
            expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expenses_pnlLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(addexpense_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2456, 2456, 2456))
                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                        .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(expenses_pnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(entryNo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                                        .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(expenses_pnlLayout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addGap(45, 45, 45))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expenses_pnlLayout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                            .addGroup(expenses_pnlLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel10)
                                                .addGap(56, 56, 56)))
                                        .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(datePickerExpensesEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amount_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(description_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expenses_pnlLayout.createSequentialGroup()
                                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                                        .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(expenses_pnlLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, expenses_pnlLayout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addComponent(btn_removeExpense)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expenses_pnlLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(datePickerExpensesSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addComponent(search_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(2361, 2361, 2361))
                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        expenses_pnlLayout.setVerticalGroup(
            expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(expenses_pnlLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(24, 24, 24)
                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(datePickerExpensesEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amount_txtfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addComponent(addexpense_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel15)
                .addGap(17, 17, 17)
                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(expenses_pnlLayout.createSequentialGroup()
                        .addComponent(datePickerExpensesSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addComponent(search_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(expenses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(entryNo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_removeExpense)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        switch_pnl.add(expenses_pnl, "card3");

        dsales_pnl.setBackground(new java.awt.Color(244, 176, 66));

        sales_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Sales", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(sales_table);

        jLabel18.setText("Show sales from:");

        btn_searchDsales.setText("OK");
        btn_searchDsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchDsalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dsales_pnlLayout = new javax.swing.GroupLayout(dsales_pnl);
        dsales_pnl.setLayout(dsales_pnlLayout);
        dsales_pnlLayout.setHorizontalGroup(
            dsales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsales_pnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dsales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dsales_pnlLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btn_searchDsales))
                    .addGroup(dsales_pnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(dsales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePickerShowSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        dsales_pnlLayout.setVerticalGroup(
            dsales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(dsales_pnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(14, 14, 14)
                .addComponent(datePickerShowSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_searchDsales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        switch_pnl.add(dsales_pnl, "card2");

        msales_pnl.setBackground(new java.awt.Color(244, 176, 66));

        msalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Year", "Sales", "Expenses", "Profit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(msalesTable);
        if (msalesTable.getColumnModel().getColumnCount() > 0) {
            msalesTable.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        jLabel19.setText("Choose year to display:");

        btnMsalesYearDisplay.setText("OK");
        btnMsalesYearDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsalesYearDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout msales_pnlLayout = new javax.swing.GroupLayout(msales_pnl);
        msales_pnl.setLayout(msales_pnlLayout);
        msales_pnlLayout.setHorizontalGroup(
            msales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msales_pnlLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(msales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msales_pnlLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19))
                    .addGroup(msales_pnlLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnMsalesYearDisplay))
                    .addGroup(msales_pnlLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        msales_pnlLayout.setVerticalGroup(
            msales_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(msales_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnMsalesYearDisplay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        switch_pnl.add(msales_pnl, "card5");

        base_pnl.add(switch_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 710, 540));

        back_pnl.setBackground(new java.awt.Color(244, 176, 66));
        back_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_pnlMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-arrow-50.png"))); // NOI18N

        javax.swing.GroupLayout back_pnlLayout = new javax.swing.GroupLayout(back_pnl);
        back_pnl.setLayout(back_pnlLayout);
        back_pnlLayout.setHorizontalGroup(
            back_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_pnlLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        back_pnlLayout.setVerticalGroup(
            back_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(24, 24, 24))
        );

        base_pnl.add(back_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 60, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(830, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_pnlMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_back_pnlMouseClicked

    private void expensesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesBtnMouseEntered
        
       // setColor(expenses);        
    }//GEN-LAST:event_expensesBtnMouseEntered

    private void expensesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesBtnMouseExited
        
       // resetColor(expenses);
    }//GEN-LAST:event_expensesBtnMouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        menu_pnl.setVisible(true);
        expenses_pnl.setVisible(false);
        dsales_pnl.setVisible(false);
        msales_pnl.setVisible(false);
        
        selectionShow(menu, expenses, sales, msales);
        Functionalities.fetch(this, Functionalities.query_menu, menu_table);
    }//GEN-LAST:event_menuMouseClicked

    private void expensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesMouseClicked
        // TODO add your handling code here:
        menu_pnl.setVisible(false);
        expenses_pnl.setVisible(true);
        dsales_pnl.setVisible(false);
        msales_pnl.setVisible(false);
        
        selectionShow(expenses, menu, sales, msales);
        Functionalities.fetch(this, Functionalities.query_expenses, expenses_table);
    }//GEN-LAST:event_expensesMouseClicked

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
        // TODO add your handling code here:
        menu_pnl.setVisible(false);
        expenses_pnl.setVisible(false);
        dsales_pnl.setVisible(true);
        msales_pnl.setVisible(false);
        
        selectionShow(sales, expenses, menu, msales);
        Functionalities.fetch(this, Functionalities.dsales_query, sales_table);
    }//GEN-LAST:event_salesMouseClicked

    private void msalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msalesMouseClicked
        // TODO add your handling code here:
        menu_pnl.setVisible(false);
        expenses_pnl.setVisible(false);
        dsales_pnl.setVisible(false);
        msales_pnl.setVisible(true);
        
        selectionShow(msales, expenses, sales, menu);
        Functionalities.fetch(this, Functionalities.msales_query, msalesTable);
    }//GEN-LAST:event_msalesMouseClicked

    private void additem_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_additem_pnlMouseClicked
        // TODO add your handling code here:
//       ----------------------INSERTING ITEM INTO MENU TABLE-------------------------------------------
           
        try {
             Class.forName(Functionalities.DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
            
            
//            ------------Checking wheter item exists in table ----------------------
            
            ResultSet result = Functionalities.table_all(this, Functionalities.query_menu);
            String check_itemcode,check_name = null;
                while(result.next()){
                   check_itemcode = result.getString("ItemCode");
                   check_name = result.getString("Name");
                   if (itemcode_txt.getText().equals(check_itemcode)){                      
                       throw new Exception();
                   } else if (name_txt.getText().equals(check_name)){
                       throw new Exception();
                   }
                }
                
                
            PreparedStatement st = connection.prepareStatement(Functionalities.insert_menu);    
            
            st.setString(1, itemcode_txt.getText());
            st.setString(2, name_txt.getText());
            st.setString(3, (String) type_combo.getSelectedItem());
            st.setString(4, price_txt.getText());
            st.execute();
            JOptionPane.showConfirmDialog(this, "Succesful Entry", "Success", JOptionPane.PLAIN_MESSAGE);
            clearMenuFields();
            
            connection.close();
        } catch (SQLException | ClassNotFoundException ex ) {
             JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
             
        } catch (NullPointerException ex){
           
            JOptionPane.showMessageDialog(this, ex);
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Item already exists", "Duplicate entry", JOptionPane.ERROR_MESSAGE);
             clearMenuFields();           
        }
        
                
    }//GEN-LAST:event_additem_pnlMouseClicked

    private void btn_alterpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterpriceActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(Functionalities.DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
//             ------------Checking wheter item exists in table ----------------------
            String query = "SELECT ItemCode FROM menu WHERE ItemCode = ?;";
            PreparedStatement stm = connection.prepareStatement(query);
            stm.setString(1, itemcode_txt2.getText());
            ResultSet result = stm.executeQuery();
            
                if (!result.isBeforeFirst()){
                    throw new Exception();
                }
//                -----------------------------------------------------------------------
            PreparedStatement st = connection.prepareStatement(Functionalities.alter_menu);
            st.setString(1, price_txt1.getText());
            st.setString(2, itemcode_txt2.getText());
            st.execute();
            
            JOptionPane.showConfirmDialog(this, "Item altered", "Success", JOptionPane.PLAIN_MESSAGE);
            clearMenuFields();
            
            connection.close();            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this, "Item not found", "ITEM NOT FOUND", JOptionPane.ERROR_MESSAGE);
             clearMenuFields();     
        }
    }//GEN-LAST:event_btn_alterpriceActionPerformed

    private void btn_removeitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeitemActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(Functionalities.DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
            
            //             ------------Checking wheter item exists in table ----------------------
            String query = "SELECT ItemCode FROM menu WHERE ItemCode = ?;";
            PreparedStatement stm = connection.prepareStatement(query);
            stm.setString(1, itemcode_txt1.getText());
            ResultSet result = stm.executeQuery();
            
                if (!result.isBeforeFirst()){
                    throw new Exception();
                }
//                -----------------------------------------------------------------------
            PreparedStatement st = connection.prepareStatement(Functionalities.remove_item);
            st.setString(1, itemcode_txt1.getText());
            st.execute();
            
            JOptionPane.showConfirmDialog(this, "Item removed", "Success", JOptionPane.PLAIN_MESSAGE);
            clearMenuFields();
            
            connection.close();
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
             JOptionPane.showMessageDialog(this, e);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Item not found", "ITEM NOT FOUND", JOptionPane.ERROR_MESSAGE);
             clearMenuFields();     
        }
    }//GEN-LAST:event_btn_removeitemActionPerformed

    private void addexpense_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addexpense_pnlMouseClicked
        // TODO add your handling code here:
//        ---------------------------Add expense to database--------------------------------
        DateFormat sqlformat = new SimpleDateFormat("yyyy-MM-dd");
        String date = sqlformat.format(datePickerExpensesEntry.getDate());
        try {
            Class.forName(Functionalities.DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
            PreparedStatement st = connection.prepareStatement(Functionalities.insert_expenses);
            st.setString(1, date);
            st.setString(2, description_txtfield.getText());
            st.setString(3, amount_txtfield.getText());
            st.execute();
            
            JOptionPane.showConfirmDialog(this, "Succesful Entry", "Success", JOptionPane.PLAIN_MESSAGE);
            clearExpenseFields();
            
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_addexpense_pnlMouseClicked

    private void search_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_pnlMouseClicked
        // TODO add your handling code here:
        DateFormat sqlformat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Class.forName(DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
            PreparedStatement st = connection.prepareStatement("SELECT * FROM `expenses` WHERE `Date` = ?;");
            st.setString(1, sqlformat.format(datePickerExpensesSearch.getDate()));
            ResultSet rS = st.executeQuery();
            
            expenses_table.setModel(DbUtils.resultSetToTableModel(rS));
            clearExpenseFieldsSearch();
            connection.close();
            
        } catch (SQLException | ClassNotFoundException | NullPointerException ex) {
             JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_search_pnlMouseClicked

    private void btn_removeExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeExpenseActionPerformed
        // TODO add your handling code here:
        try {
             Class.forName(DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
//            ------------------Checking whether entry exists--------------------------------
            PreparedStatement stm = connection.prepareStatement("SELECT EntryNo FROM expenses WHERE EntryNo = ?;");
            stm.setString(1,entryNo_txtfield.getText());
            ResultSet rs = stm.executeQuery();
            if (!rs.isBeforeFirst()){
                throw new Exception();
            }
            PreparedStatement st = connection.prepareStatement(Functionalities.remove_expense);
            st.setString(1, entryNo_txtfield.getText());
            st.execute();
            
            JOptionPane.showConfirmDialog(this, "Entry removed", "Success", JOptionPane.PLAIN_MESSAGE);
            clearExpenseFields();
            
            connection.close();
        } catch (SQLException | ClassNotFoundException e) {
              JOptionPane.showMessageDialog(this, e);
        } catch (Exception ex) {
              JOptionPane.showMessageDialog(this, "Entry not found", "ENTRY NOT FOUND", JOptionPane.ERROR_MESSAGE);
              clearExpenseFields();
        }
                
    }//GEN-LAST:event_btn_removeExpenseActionPerformed

    private void btn_searchDsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchDsalesActionPerformed
        // TODO add your handling code here:
        DateFormat sqlformat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Class.forName(DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
            PreparedStatement st = connection.prepareStatement(Functionalities.dsale_search);
            st.setString(1, sqlformat.format(datePickerShowSales.getDate()));
            ResultSet rs = st.executeQuery();
            
            sales_table.setModel(DbUtils.resultSetToTableModel(rs));
            clearExpenseFields();
            connection.close();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
        }
        datePickerShowSales.setDate(null);
    }//GEN-LAST:event_btn_searchDsalesActionPerformed

    private void btnMsalesYearDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsalesYearDisplayActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName(DRIVER);
            
            connection = DriverManager.getConnection(Functionalities.URL, Functionalities.USER, Functionalities.PASSWORD);
            PreparedStatement st = connection.prepareStatement(Functionalities.msales_search);
            st.setString(1,Integer.toString(jYearChooser1.getYear()));
            ResultSet rs = st.executeQuery();
            
            msalesTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnMsalesYearDisplayActionPerformed

// ---------------------   Changing background color of buttons for responsive feel ---------------
    
    public void setColor(JPanel panel){
        
          panel.setBackground(new Color(202, 244, 65));  
               
    }
    public void resetColor(JPanel panel){
        
            panel.setBackground(new Color(185, 244, 66));
                    
    }
    
//   -----------------------------  END  ------------------------------------------------------- 
    
//    ---------------Clearing the input fields and updates the table display---------------------
    
    public void clearMenuFields(){
        itemcode_txt.setText("");
        name_txt.setText("");
        type_combo.setSelectedIndex(-1);
        price_txt.setText("");
        itemcode_txt1.setText("");
        itemcode_txt2.setText("");
        price_txt1.setText("");
        Functionalities.fetch(this, Functionalities.query_menu, menu_table);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Admin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addexpense_pnl;
    private javax.swing.JPanel additem_pnl;
    private javax.swing.JTextField amount_txtfield;
    private javax.swing.JPanel back_pnl;
    private javax.swing.JPanel base_pnl;
    private javax.swing.JButton btnMsalesYearDisplay;
    private javax.swing.JButton btn_alterprice;
    private javax.swing.JButton btn_removeExpense;
    private javax.swing.JButton btn_removeitem;
    private javax.swing.JButton btn_searchDsales;
    private org.jdesktop.swingx.JXDatePicker datePickerExpensesEntry;
    private org.jdesktop.swingx.JXDatePicker datePickerExpensesSearch;
    private org.jdesktop.swingx.JXDatePicker datePickerShowSales;
    private javax.swing.JTextField description_txtfield;
    private javax.swing.JPanel dsales_pnl;
    private javax.swing.JTextField entryNo_txtfield;
    private javax.swing.JPanel expenses;
    private javax.swing.JPanel expenses_pnl;
    private javax.swing.JTable expenses_table;
    private javax.swing.JTextField itemcode_txt;
    private javax.swing.JTextField itemcode_txt1;
    private javax.swing.JTextField itemcode_txt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menu_pnl;
    private javax.swing.JTable menu_table;
    private javax.swing.JPanel msales;
    private javax.swing.JTable msalesTable;
    private javax.swing.JPanel msales_pnl;
    private javax.swing.JTextField name_txt;
    private javax.swing.JPanel nav_pnl;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField price_txt1;
    private javax.swing.JPanel sales;
    private javax.swing.JTable sales_table;
    private javax.swing.JPanel search_pnl;
    private javax.swing.JPanel switch_pnl;
    private javax.swing.JComboBox<String> type_combo;
    // End of variables declaration//GEN-END:variables

    private void clearExpenseFields() {
       amount_txtfield.setText("");
       description_txtfield.setText("");
       entryNo_txtfield.setText("");
       datePickerExpensesEntry.setDate(null);
       datePickerExpensesSearch.setDate(null);
       Functionalities.fetch(this, Functionalities.query_expenses, expenses_table);
    }
    
    private void selectionShow(JPanel one, JPanel two, JPanel three, JPanel four){
        setColor(one);
        resetColor(two);
        resetColor(three);
        resetColor(four);
    }

    private void clearExpenseFieldsSearch() {
        amount_txtfield.setText("");
       description_txtfield.setText("");
       entryNo_txtfield.setText("");
       datePickerExpensesEntry.setDate(null);
       datePickerExpensesSearch.setDate(null);
    }
     
   
}
